services:
  frontend:
    build:
      context: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./back
    ports:
      - 8000:8000
    volumes:
      - ./back:/var/www
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=todo_db
    volumes:
      - todo-app:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  todo-app:
